#!/usr/bin/env ruby
######################################################################
##           Script for launching the simplify_qm.rb program        ##
######################################################################

Dir.chdir "../lib/logic_tools"

load "simplify_qm.rb"
