#!/usr/bin/env ruby
######################################################################
##              Script for launching the simplify.rb program        ##
######################################################################

Dir.chdir "../lib/logic_tools"

load "std_conj.rb"
