#!/usr/bin/env ruby
######################################################################
##              Script for launching the simplify.rb program        ##
######################################################################

begin
    require 'rubygems'
    gem 'logic_tools'
rescue LoadError
end

load "logic_tools/truth_tbl.rb"
